### ISSUE TITLE
New version of Parson available

### ISSUE THREAD

**Issue by dnorthup-ums** [duosecurity/libduo#10]
Is there some reason why this hasn't been updated to use a newer version of https://github.com/kgabis/parson ?

**Comment by xdesai** [comment]
No particular reason! This repository has been low use and relatively stable so we just haven't had the urgency to update it.
There's some work in the pipeline surrounding this repository so we will definitely look lumping in a Parson update when we get around to making those other changes.

Thanks for bringing it to our attention!
