### ISSUE TITLE
Inquiry Regarding Code Differences Between libduo and duo_unix

### ISSUE THREAD

**Issue by srinidm** [duosecurity/libduo#18]
Hi Team,

I hope this message finds you well. I am currently integrating the libduo to my application, and I have come across a couple of points that I would appreciate your insights on.

In the duo_auth_auth function of libduo, I noticed the following comment: "Disable timeout for this call". The corresponding lines of code are:
https_timeout = ctx->https_timeout;
ctx->https_timeout = DUO_NO_TIMEOUT;

This seems to differ from the equivalent function in duo_unix. Could you kindly explain the specific reason for this discrepancy? Furthermore, would there be any impact on functionality if I were to remove these lines from libduo?

I also observed a three-time loop in the _establish_connection function at https://github.com/duosecurity/libduo/blob/master/https.c#L284. Could you please elaborate on the specific reason for this implementation? I am considering removing the while loop and would like to understand if this modification could potentially affect the functionality.

Thank you very much for your time and assistance. I look forward to hearing from you.

Regards,
Srinidhi

**Comment by DuoKristina** [comment]
1. The implementation in duo_unix lets the admin configure the timeout via a .conf file.

2. We have a configurable fail mode in duo_unix which determines if the client should let login continue if it can't connect to Duo's service or not. So it tries three times and if it can't establish connectivity for auth it proceeds to either fail open or fail closed as set in the conf file.

**Comment by srinidm** [comment]
Thank you for your response.

I'm considering making a couple of modifications to the libduo library and would appreciate your insights on potential side effects.

Firstly, I plan to comment out the following lines in the duo_auth_auth function:

//https_timeout = ctx->https_timeout;
//ctx->https_timeout = DUO_NO_TIMEOUT;

I intend to set the timeout using the duo_set_timeout(duo, 30) function. 
My goal is to have a defined timeout period rather than disabling the timeout completely.

Secondly, I am considering modifying the retry loop in the _establish_connection function.
Currently, in case of a failure, it takes approximately 3 minutes for the function to return. I believe this is due to the retry loop:

for (cur_res = res; cur_res; cur_res = cur_res->ai_next) {
    int connretries = 3;
    while (connected_socket == -1 && connretries--) {
        int sock_flags;

I plan to change connretries = 1 to remove the retry mechanism and allow the function to return earlier in case of a failure. I have tested this change and found that the function returns in approximately 67 to 70 seconds in case of a failure.

Could you please let me know if these changes could potentially lead to any side effects or unexpected behavior in the library's functionality? I appreciate your guidance on this matter.

P.S: Even I have the logic of fail mode. So, incase of timeout, I will allow/disallow based on the fail mode configuration.

**Comment by DuoKristina** [comment]
Yeah, that should be fine. You could safely make the timeout for the initial connect even shorter i.e. 20 seconds.
