### ISSUE TITLE
Documentation is out of sync with duo_auth_preauth()

### ISSUE THREAD

**Issue by ivmaykov** [duosecurity/libduo#2]
The API documentation at https://duo.com/docs/authapi#/preauth is out of sync with the implementation of duo_auth_preauth(). Specifically, the documentation does not mention the "prompt" element of the JSON response. This is actually a bug with the docs page rather than the C library, but I didn't see a link to submit bug reports on the docs page. Please route this to the documentation people :)

**Comment by erikbarbara** [comment]
Hi @ivmaykov, we'll look into this. Thanks!

**Comment by BradleyHiggins** [comment]
Good eye!  The "prompt" element was originally implemented to ease the transition from AuthAPI v1 to AuthAPI v2, but it was intentionally left undocumented.  We encourage you to not rely on it when using the Auth API.

Thanks for using Duo!
