### ISSUE TITLE
About the test

### ISSUE THREAD

**Issue by Tigerly** [duosecurity/libduo#3]
Hello,
I've already built the libduo on my ubuntu system.
I was wondering how to test it?
For example, about 
 DUO_API_HOST=<host-here> DUO_IKEY=<ikey-here> DUO_SKEY=<skey-here> ./test-duologin <username>

how can I get the host, ikey, skey and my username?
I've already have a account of DUO in my cell phone. Can I use this tool to send a message to the DUO app in my phone? 

Thanks in advance!

**Comment by xdesai** [comment]
Hi @Tigerly,
The api host, ikey, and skey are values that you will take out the Duo Admin Panel.
In the admin panel create an Application type of Auth API and use the ikey, skey, and api host from there. 
This link might be helpful for you https://duo.com/docs/getting_started
-Xander

**Comment by Tigerly** [comment]
Got it. Thanks a lot :)
