### ISSUE TITLE
Please add support for building with OpenSSL 1.1.x

### ISSUE THREAD

**Issue by ljakab** [duosecurity/libduo#4]
OpenSSL 1.1.x deprecated some of the HMAC_* functions used by this code, which no longer builds against this newer OpenSSL version, which is shipped by default for example in Ubuntu 18.04 LTS. Other projects have faced similar issues, one solution for NGINX for example can be found in [this commit](https://github.com/arut/nginx-rtmp-module/commit/04f0ab97ac61d181dbfdaa5299412fc3064e95a3). I made similar changes to make the code build, but there are still a lot of warnings which would need to be cleaned up for OpenSSL 1.1.x

**Comment by xdesai** [comment]
Hello!
Thanks for bringing this to our attention.
We addressed what sounds like a similar issue in our Duo Unix repository, but it looks like we forgot to fix that here as well.
No timeline for a fix just yet, but I'll make sure this gets tracked!

**Comment by ljakab** [comment]
Thanks! I just found the [relevant commit](https://github.com/duosecurity/duo_unix/commit/673b3ce97763530d09f8a2002959b6b45214ac1a) in Duo Unix, that helps temporarily.

**Comment by z-tb** [comment]
@xdesai I needed to compile libduo on Ubuntu 18.04 (as well as 16.04) so forked it and worked in some conditional compilation directives to get it built.  Any interest in a pull request?

**Comment by xdesai** [comment]
Hi @z-tb!
Sorry we haven't had a chance to get this work done. If you make a pull request for this feature we'd be happy to take a look.

**Comment by z-tb** [comment]
No problem. Glad you guys have made so much of the source available. I've submitted the PR.

**Comment by dnorthup-ums** [comment]
@mschwager & @xdesai Is there an ETA on this? If we decide to implement @ $dayjob our CISO is likely to want to know, especially if duosecurity/duo_unix gets upgraded to use the V2 API.

**Comment by xdesai** [comment]
I believe we actually got this resolved awhile back and just forgot to close the issue!
You should be all set to use libduo with openssl 1.1.X. Let us know if that doesn't seem to be working
https://github.com/duosecurity/libduo/commit/d8f8895f9c4afdfa83b142d34606a017eedd7a3d
